# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "custom-field-js"
client_id = "8695ec50e3a2fc6ba52afcda7e27b182"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
